import './frame-flow';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const base = process.env.GALLERY_TEST_BASE_URL ?? 'http://127.0.0.1:3000';
const session = await fetch(base + '/api/session', process.env.GALLERY_TEST_PASSWORD ? { method: 'POST', headers: { Origin: base, 'Content-Type': 'application/json' }, body: JSON.stringify({ password: process.env.GALLERY_TEST_PASSWORD }) } : undefined);
assert.equal(session.status, 200);
const headers = { Cookie: session.headers.get('set-cookie')!.split(';')[0], Origin: base, 'Content-Type': 'application/json' };
const {galleryId, artworkId, shareToken} = JSON.parse(await readFile('.gallery-twin/frame-check.json', 'utf8'));
const path = '/api/galleries/' + galleryId;
let detail = await (await fetch(base + path, {headers})).json();
const placed = detail.exhibition.placements.find((p: any) => p.artworkId === artworkId);
assert.ok(placed);
const scene = {...detail.scene, observers: [{id: 'delete-observer', placementId: placed.id, heightMm: 1700}]};
const save = await fetch(base + path, {method:'PATCH',headers,body:JSON.stringify({scene, placements: detail.exhibition.placements, expectedRevision: detail.exhibition.revision})});
assert.equal(save.status,200);
detail = await (await fetch(base + path,{headers})).json();
const url = base + '/api/artworks/' + artworkId;
const remove = (revision: number) => fetch(url,{method:'DELETE',headers,body:JSON.stringify({expectedRevision:revision})});
assert.equal((await fetch(url,{method:'DELETE',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:detail.exhibition.revision})})).status,401);
assert.equal((await remove(detail.exhibition.revision-1)).status,409);
assert.equal((await remove(detail.exhibition.revision)).status,200);
const after = await (await fetch(base+path,{headers})).json();
assert.ok(!after.artworks.some((a:any)=>a.id===artworkId));
assert.ok(!after.exhibition.placements.some((p:any)=>p.artworkId===artworkId));
assert.ok(!after.scene.observers.some((o:any)=>o.id==='delete-observer'));
assert.equal(after.exhibition.revision,detail.exhibition.revision+1);
assert.equal((await remove(after.exhibition.revision)).status,404);
const shared = await (await fetch(base+'/api/shares/'+shareToken)).json();
const sharedArt = shared.artworks.find((a:any)=>a.id===artworkId);
assert.ok(sharedArt);
assert.equal((await fetch(base+sharedArt.imageUrl)).status,200);
console.log('PASS: deletion persists, removes placements and observers, rejects stale revisions, and preserves frozen share images.');
